import { brandColors } from "../src/lib/colors";
import { imageForColour } from "../src/lib/colour-images";

function paletteHex(name: string, fallback: string) {
  return brandColors.find((c) => c.name === name)?.hex ?? fallback;
}

/** Build a colour variant with a unique image per shade. */
function colour(name: string, alt: string, category: string, imageOverride?: string) {
  return {
    name,
    hex: paletteHex(name, "#888888"),
    images: [{ url: imageOverride ?? imageForColour(name, category), kind: "front", alt: `${alt} — ${name}` }],
  };
}

export type SeedProduct = {
  name: string;
  slug: string;
  sku: string;
  category: string;
  collections: string[];
  description: string;
  shortDescription: string;
  fit: string;
  fabric: string;
  pattern: string;
  neck?: string;
  sleeve?: string;
  care: string;
  colours: { name: string; hex: string; images: { url: string; kind: string; alt: string }[] }[];
  price: number;
  mrp: number;
  isNew?: boolean;
  isBestseller?: boolean;
  isLimited?: boolean;
};

const tee = "/images/product-oversized-tee.jpg";
const white = "/images/product-white-tee.jpg";
const cargo = "/images/product-cargo.jpg";
const trouser = "/images/product-trouser.jpg";
const denim = "/images/product-denim.jpg";
const shirt = "/images/product-shirt.jpg";
const hoodie = "/images/product-hoodie.jpg";
const coord = "/images/product-coord.jpg";
const varsity = "/images/product-varsity.jpg";
const parachute = "/images/product-parachute.jpg";
const bomber = "/images/product-bomber.jpg";
const denimJ = "/images/product-denim-jacket.jpg";
const red = "/images/product-red-tee.jpg";

/** Premium muted palette + modern relaxed silhouettes. Matte fabrics only. */
export const catalogProducts: SeedProduct[] = [
  {
    name: "Boxy Heavyweight Tee",
    slug: "boxy-heavyweight-tee",
    sku: "BB-TEE-BOX-001",
    category: "t-shirts",
    collections: ["essentials", "best-sellers", "new-drop"],
    shortDescription: "240 GSM boxy cut. Dropped shoulder.",
    description: "Heavy 240 GSM cotton with a boxy silhouette, dropped shoulders, and a tight ribbed crew. Matte dry hand-feel. Ecru, pitch black, and heather grey — core neutrals that sell year-round.",
    fit: "Boxy",
    fabric: "240 GSM cotton",
    pattern: "Solid",
    neck: "Ribbed crew",
    sleeve: "Short",
    care: "Machine wash cold. Dry in shade.",
    colours: [
      colour("Ecru", "Boxy Heavyweight Tee", "t-shirts"),
      colour("Chalk", "Boxy Heavyweight Tee", "t-shirts"),
      colour("Pitch Black", "Boxy Heavyweight Tee", "t-shirts"),
      colour("Heather Grey", "Boxy Heavyweight Tee", "t-shirts"),
      colour("Sand", "Boxy Heavyweight Tee", "t-shirts"),
      colour("Warm Taupe", "Boxy Heavyweight Tee", "t-shirts"),
    ],
    price: 1299,
    mrp: 1899,
    isBestseller: true,
    isNew: true,
  },
  {
    name: "Relaxed Graphic Tee",
    slug: "relaxed-graphic-tee",
    sku: "BB-TEE-GRF-002",
    category: "t-shirts",
    collections: ["streetwear", "new-drop"],
    shortDescription: "Vintage wash. Minimal front mark.",
    description: "Relaxed fit tee in acid-washed cotton with minimal front typography and a large tonal back graphic. Terracotta and washed charcoal — muted, not loud.",
    fit: "Relaxed",
    fabric: "220 GSM washed cotton",
    pattern: "Graphic",
    neck: "Crew",
    sleeve: "Short",
    care: "Wash inside out. Cold water.",
    colours: [colour("Terracotta", "Relaxed Graphic Tee", "t-shirts"), colour("Washed Charcoal", "Relaxed Graphic Tee", "t-shirts")],
    price: 1499,
    mrp: 2199,
    isNew: true,
  },
  {
    name: "Cobalt Statement Tee",
    slug: "cobalt-statement-tee",
    sku: "BB-TEE-COB-003",
    category: "t-shirts",
    collections: ["streetwear", "limited-edition"],
    shortDescription: "Muted cobalt boxy tee.",
    description: "Seasonal accent piece in a deep matte cobalt — statement without gloss. Boxy heavyweight cut.",
    fit: "Boxy",
    fabric: "240 GSM cotton",
    pattern: "Solid",
    neck: "Crew",
    sleeve: "Short",
    care: "Machine wash cold.",
    colours: [colour("Cobalt", "Cobalt Statement Tee", "t-shirts")],
    price: 1399,
    mrp: 1999,
    isLimited: true,
  },
  {
    name: "Washed Mint Summer Tee",
    slug: "washed-mint-tee",
    sku: "BB-TEE-MNT-004",
    category: "t-shirts",
    collections: ["summer", "new-drop"],
    shortDescription: "Pastel sage wash.",
    description: "Relaxed summer tee in washed mint — a muted pastel, never neon. Lightweight matte cotton.",
    fit: "Relaxed",
    fabric: "200 GSM cotton",
    pattern: "Solid",
    neck: "Crew",
    sleeve: "Short",
    care: "Gentle wash.",
    colours: [colour("Washed Mint", "Washed Mint Summer Tee", "t-shirts")],
    price: 999,
    mrp: 1499,
    isNew: true,
  },
  {
    name: "Cuban Camp Shirt",
    slug: "cuban-camp-shirt",
    sku: "BB-SHT-CUB-005",
    category: "shirts",
    collections: ["summer", "essentials"],
    shortDescription: "Open collar. Linen blend.",
    description: "Cuban collar camp shirt in a fluid linen-viscose blend. Boxy hem, matte texture. Sand, dusty rose, and ink navy.",
    fit: "Cuban",
    fabric: "Linen-viscose blend",
    pattern: "Solid",
    neck: "Open collar",
    sleeve: "Short",
    care: "Gentle wash or dry clean.",
    colours: [
      colour("Sand", "Cuban Camp Shirt", "shirts"),
      colour("Dusty Rose", "Cuban Camp Shirt", "shirts", red),
      colour("Ink Navy", "Cuban Camp Shirt", "shirts"),
    ],
    price: 1899,
    mrp: 2699,
    isBestseller: true,
  },
  {
    name: "Structured Overshirt",
    slug: "structured-overshirt",
    sku: "BB-SHT-OVR-006",
    category: "shirts",
    collections: ["streetwear", "winter"],
    shortDescription: "Heavy twill shacket.",
    description: "Structured overshirt in dry cotton twill with dual flap chest pockets. Worn open over a tee. Olive and washed charcoal.",
    fit: "Overshirt",
    fabric: "Cotton twill",
    pattern: "Solid",
    neck: "Point collar",
    sleeve: "Long",
    care: "Machine wash cold.",
    colours: [colour("Olive", "Structured Overshirt", "shirts"), colour("Washed Charcoal", "Structured Overshirt", "shirts")],
    price: 2799,
    mrp: 3799,
    isNew: true,
  },
  {
    name: "Knit Resort Polo",
    slug: "knit-resort-polo",
    sku: "BB-POL-KNT-007",
    category: "polos",
    collections: ["summer", "essentials"],
    shortDescription: "Johnny collar open knit.",
    description: "Resort polo in ribbed open-knit cotton with a Johnny collar. Mocha and chalk — knitwear polish, matte finish.",
    fit: "Resort",
    fabric: "Open-knit cotton",
    pattern: "Solid",
    neck: "Johnny collar",
    sleeve: "Short",
    care: "Hand wash or delicate cycle.",
    colours: [colour("Mocha", "Knit Resort Polo", "polos"), colour("Chalk", "Knit Resort Polo", "polos")],
    price: 1699,
    mrp: 2499,
  },
  {
    name: "Baggy Denim",
    slug: "baggy-denim",
    sku: "BB-JNS-BAG-008",
    category: "jeans",
    collections: ["streetwear", "best-sellers", "new-drop"],
    shortDescription: "Wide leg. Vintage wash.",
    description: "Baggy fit denim with a mid rise, wide thigh and calf, and slight stack over sneakers. Washed black and ecru — no glossy indigo.",
    fit: "Baggy",
    fabric: "14oz denim",
    pattern: "Solid",
    care: "Wash inside out. Rarely.",
    colours: [
      colour("Pitch Black", "Baggy Denim", "jeans", denim),
      colour("Ecru", "Baggy Denim", "jeans", white),
    ],
    price: 2899,
    mrp: 3999,
    isBestseller: true,
    isNew: true,
  },
  {
    name: "Straight Denim",
    slug: "straight-denim",
    sku: "BB-JNS-STR-009",
    category: "jeans",
    collections: ["essentials"],
    shortDescription: "Clean straight leg.",
    description: "Non-distressed straight-leg denim with a clean raw hem. Slate grey wash — industrial and matte.",
    fit: "Straight",
    fabric: "13oz denim",
    pattern: "Solid",
    care: "Wash inside out.",
    colours: [colour("Slate Grey", "Straight Denim", "jeans")],
    price: 2699,
    mrp: 3699,
  },
  {
    name: "Pleated Relaxed Trouser",
    slug: "pleated-relaxed-trouser",
    sku: "BB-TRS-PLT-010",
    category: "trousers",
    collections: ["essentials", "best-sellers"],
    shortDescription: "Front pleat. Wide drape.",
    description: "Single front pleat, relaxed wide leg, semi-elasticated waistband in matte poly-viscose. Stone, warm taupe, and ink navy.",
    fit: "Pleated",
    fabric: "Poly-viscose twill",
    pattern: "Solid",
    care: "Dry clean preferred.",
    colours: [
      colour("Stone", "Pleated Relaxed Trouser", "trousers"),
      colour("Warm Taupe", "Pleated Relaxed Trouser", "trousers", coord),
      colour("Ink Navy", "Pleated Relaxed Trouser", "trousers", denimJ),
    ],
    price: 2299,
    mrp: 3299,
    isBestseller: true,
  },
  {
    name: "Camel Baggy Trouser",
    slug: "camel-baggy-trouser",
    sku: "BB-TRS-CML-011",
    category: "trousers",
    collections: ["winter", "streetwear"],
    shortDescription: "Baggy drape in camel.",
    description: "Trend-forward baggy trouser in a matte camel faux-suede touch poly blend. Relaxed through the leg.",
    fit: "Baggy",
    fabric: "Poly blend",
    pattern: "Solid",
    care: "Dry clean.",
    colours: [colour("Camel", "Camel Baggy Trouser", "trousers", bomber)],
    price: 2499,
    mrp: 3499,
    isNew: true,
  },
  {
    name: "Parachute Utility Cargo",
    slug: "parachute-utility-cargo",
    sku: "BB-CRG-PAR-012",
    category: "cargos",
    collections: ["streetwear", "new-drop", "best-sellers"],
    shortDescription: "6-pocket wide leg.",
    description: "Wide-leg parachute cargo with six pockets and ankle drawcords. Toggle between wide and tapered. Olive, sage, and pitch black — utility matte nylon.",
    fit: "Parachute",
    fabric: "Matte nylon",
    pattern: "Solid",
    care: "Gentle wash.",
    colours: [
      colour("Olive", "Parachute Utility Cargo", "cargos"),
      colour("Sage", "Parachute Utility Cargo", "cargos"),
      colour("Pitch Black", "Parachute Utility Cargo", "cargos", denim),
    ],
    price: 2599,
    mrp: 3599,
    isBestseller: true,
    isNew: true,
  },
  {
    name: "Minimal Drop-Shoulder Hoodie",
    slug: "minimal-hoodie",
    sku: "BB-HOD-MIN-013",
    category: "hoodies",
    collections: ["winter", "essentials"],
    shortDescription: "Clean french terry. No noise.",
    description: "Heavy french-terry hoodie with drop shoulders, minimal kangaroo pouch, and hidden drawcord channel for a clean line. Heather grey and pitch black.",
    fit: "Minimal",
    fabric: "450 GSM french terry",
    pattern: "Solid",
    neck: "Hood",
    sleeve: "Long",
    care: "Wash cold.",
    colours: [colour("Heather Grey", "Minimal Drop-Shoulder Hoodie"), colour("Pitch Black", "Minimal Drop-Shoulder Hoodie", "hoodies", tee)],
    price: 2799,
    mrp: 3799,
    isBestseller: true,
  },
  {
    name: "Waffle Co-ord Set",
    slug: "waffle-coord-set",
    sku: "BB-SET-WAF-014",
    category: "co-ords",
    collections: ["summer", "new-drop", "limited-edition"],
    shortDescription: "Matching waffle knit set.",
    description: "Textured waffle-knit button shirt with matching drawstring shorts. Sand and ecru — resort uniform, matte texture.",
    fit: "Relaxed",
    fabric: "Waffle cotton",
    pattern: "Solid",
    sleeve: "Short",
    care: "Gentle wash as a set.",
    colours: [colour("Sand", "Waffle Co-ord Set"), colour("Ecru", "Waffle Co-ord Set", "co-ords", white)],
    price: 4499,
    mrp: 5999,
    isLimited: true,
    isNew: true,
  },
  {
    name: "Matte Bomber Jacket",
    slug: "matte-bomber",
    sku: "BB-JKT-BMB-015",
    category: "jackets",
    collections: ["winter", "streetwear"],
    shortDescription: "Satin nylon bomber.",
    description: "Matte satin nylon bomber with rib hem and two-way zip. Ink navy and washed charcoal — no high-gloss shell.",
    fit: "Regular",
    fabric: "Matte satin nylon",
    pattern: "Solid",
    sleeve: "Long",
    care: "Gentle wash.",
    colours: [colour("Ink Navy", "Matte Bomber Jacket"), colour("Washed Charcoal", "Matte Bomber Jacket", "jackets", tee)],
    price: 3999,
    mrp: 5499,
  },
  {
    name: "Varsity Jacket",
    slug: "varsity-jacket",
    sku: "BB-JKT-VAR-016",
    category: "jackets",
    collections: ["limited-edition", "winter"],
    shortDescription: "Wool blend. Matte sleeves.",
    description: "Varsity jacket in wool-blend body with matte faux-leather sleeves. Mocha and camel colourway — earth tones, not glossy.",
    fit: "Regular",
    fabric: "Wool blend / matte faux leather",
    pattern: "Colourblock",
    sleeve: "Long",
    care: "Dry clean.",
    colours: [colour("Mocha", "Varsity Jacket"), colour("Camel", "Varsity Jacket", "jackets", coord)],
    price: 4999,
    mrp: 6999,
    isLimited: true,
  },
  {
    name: "Sage Oversized Tee",
    slug: "sage-oversized-tee",
    sku: "BB-TEE-SAG-017",
    category: "t-shirts",
    collections: ["essentials", "summer"],
    shortDescription: "Muted sage green.",
    description: "Oversized tee in a dusty sage green — earth tone utility, matte cotton. Pairs with olive cargos.",
    fit: "Oversized",
    fabric: "220 GSM cotton",
    pattern: "Solid",
    neck: "Crew",
    sleeve: "Short",
    care: "Machine wash cold.",
    colours: [colour("Sage", "Sage Oversized Tee", "t-shirts")],
    price: 1199,
    mrp: 1699,
  },
  {
    name: "Essential Sweatshirt",
    slug: "essential-sweatshirt",
    sku: "BB-SWT-ESS-018",
    category: "sweatshirts",
    collections: ["winter", "essentials"],
    shortDescription: "400 GSM loopknit crew.",
    description: "Set-in sleeve sweatshirt in 400 GSM loopknit fleece. Warm taupe and heather grey — core neutral layering.",
    fit: "Oversized",
    fabric: "400 GSM fleece",
    pattern: "Solid",
    neck: "Crew",
    sleeve: "Long",
    care: "Wash cold.",
    colours: [colour("Warm Taupe", "Essential Sweatshirt", "sweatshirts"), colour("Heather Grey", "Essential Sweatshirt", "sweatshirts")],
    price: 2299,
    mrp: 3199,
  },
  {
    name: "Essential Relaxed Tee",
    slug: "essential-relaxed-tee",
    sku: "BB-TEE-REL-019",
    category: "t-shirts",
    collections: ["essentials", "best-sellers", "summer"],
    shortDescription: "220 GSM relaxed fit. Six core shades.",
    description: "Everyday relaxed tee in soft matte cotton. One style, six colourways — ecru, olive, terracotta, ink navy, sage, and washed mint. Each shade has its own product image.",
    fit: "Relaxed",
    fabric: "220 GSM cotton",
    pattern: "Solid",
    neck: "Crew",
    sleeve: "Short",
    care: "Machine wash cold.",
    colours: [
      colour("Ecru", "Essential Relaxed Tee", "t-shirts"),
      colour("Olive", "Essential Relaxed Tee", "t-shirts"),
      colour("Terracotta", "Essential Relaxed Tee", "t-shirts"),
      colour("Ink Navy", "Essential Relaxed Tee", "t-shirts"),
      colour("Sage", "Essential Relaxed Tee", "t-shirts"),
      colour("Washed Mint", "Essential Relaxed Tee", "t-shirts"),
    ],
    price: 1099,
    mrp: 1599,
    isBestseller: true,
  },
];
